// Phase 13 - Comprehensive Documentation Generator
// Creates all 18 required docs per §59 of the Phase 13 Remediation prompt

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const docsDir = path.join(__dirname, '../../docs');

// Evidence snapshot hash (generated by generate_phase13_snapshot.js):
// a3460569f2d81982a4c0ecf62836ae2367fcd8b674b8117615281952e1caa9ee

const docs = {
'PHASE_13_BETA_STRATEGY.md': `# Phase 13 — Beta Strategy

## Objective
Transition FinCopilot from engineered code to observed real-user behavior.

## Beta Philosophy
Beta is NOT "everyone is happy." Beta is:
- Controlled exposure
- Real measurement
- Failure discovery
- Trust validation

A high-quality beta may produce many failures. That is useful evidence.

## Stages
\`\`\`
INTERNAL → FRIENDS/TESTERS → SMALL INVITED BETA → EXPANDED BETA
\`\`\`

Gate progression is based on evidence, not calendar dates.

## Current Status
- REAL USERS = 0 (pre-launch, infrastructure ready)
- Phase 13 status: OPEN — awaiting real user onboarding

## Entry Contract for Phase 14
Before declaring Phase 13 VERIFIED_COMPLETE, the product must have:
- Real user evidence (N > 0)
- Controlled, privacy-safe telemetry confirmed active
- No unresolved P0/P1 incidents
- Frozen versioned evidence snapshot with real hash
`,

'PHASE_13_COHORT_DESIGN.md': `# Phase 13 — Cohort Design

## Cohort Schema
\`\`\`
cohort_id          TEXT
eligibility        DEFINED (see below)
entry_date         TIMESTAMPTZ
feature_flags      ai_forecast_beta, automated_corrections, new_trust_dashboard
consent_state      REQUIRED
region             POLICY_REQUIRED
\`\`\`

## Eligibility Requirements
- Authenticated user ✓
- Valid consent on file ✓
- Not a test/developer account ✓
- betaRegionApproved: POLICY_REQUIRED (blocking enrollment until defined)

## Cohort Assignment
Handled by \`backend/utils/beta-cohort.js\`:
- INTERNAL: explicit invite (betaRole === 'INTERNAL')
- BETA_COHORT_1: deterministic percentage bucket (< 5%)
- Assignment persisted in \`beta_cohort_assignments\` table (migration 0020)
- No cohort switching mid-measurement

## Test Traffic Isolation
- isTestAccount flag blocks test users from cohort assignment
- X-Traffic-Class header marks synthetic/load test requests
- TrafficClass enum enforced in Telemetry service

## Current State
Real users enrolled: 0
`,

'PHASE_13_ONBOARDING.md': `# Phase 13 — Onboarding Measurement

## Activation Definition
**Selected Definition:** \`FIRST_TRUSTED_FINANCIAL_RESULT_VIEWED\`
This fires server-side when a user successfully receives a verified financial state response.
It does NOT fire on: app open, sign-in alone, or empty state display.

## Onboarding Funnel Events
Each event fires ONLY after the real server-side condition is met:

| Step | Event | Condition |
|------|-------|-----------|
| 1 | ONBOARDING_BETA_INVITED | Invite sent by admin |
| 2 | ONBOARDING_BETA_ACCEPTED | User clicked accept link |
| 3 | ONBOARDING_SIGNED_IN | Auth token verified server-side |
| 4 | ONBOARDING_CONSENTED | Consent record persisted to DB |
| 5 | ONBOARDING_DATA_SOURCE_CONNECTED | First connection row written |
| 6 | ONBOARDING_FIRST_DATA_READY | First sync completed successfully |
| 7 | ONBOARDING_FIRST_AI_QUERY | AI endpoint responded with result |
| 8 | ONBOARDING_FIRST_USEFUL_RESULT | User marked response helpful |
| 9 | ONBOARDING_FIRST_CORRECTION | Correction persisted + downstream updated |
| 10 | ONBOARDING_FIRST_PLANNING_ACTION | Goal/plan record created |

## Implementation
All funnel events implemented in \`Telemetry.trackOnboardingStep()\` with step validation.

## Current Metrics
N = 0 real users. INSUFFICIENT_EVIDENCE until onboarding begins.
`,

'PHASE_13_DATA_QUALITY.md': `# Phase 13 — Data Quality

## Metrics to Track (Real Beta Users)
| Metric | Definition |
|--------|-----------|
| freshness | Age of latest sync per user (hours) |
| coverage | % of known accounts with recent data |
| connection_success | Successful connections / attempts |
| sync_completed | Successful syncs / started |
| parse_success | Parsed rows / total rows |
| stale_rate | Accounts not synced in > 24h |
| normalization_review | Records requiring manual review |
| reconciliation_conflicts | Active conflicts needing resolution |

## Endpoint
GET /api/v1/internal/data-quality — requires new_trust_dashboard flag.
Returns aggregate connection health from \`user_connections\` table.

## Privacy Rule
No user-level sensitive payload in generic analytics. Aggregated counts only.

## Current Status
INSUFFICIENT_EVIDENCE — N = 0 real users.
`,

'PHASE_13_CORRECTION_QUALITY.md': `# Phase 13 — Correction Quality

## Correction Definition
A correction is COMPLETE only when:
1. Backend persists valid correction to canonical state
2. Downstream financial state is updated OR correctly marked stale

A UI click alone is NOT a successful correction.

## Correction Event Model
\`\`\`
correction_id       UUID
user_scope          anon_user_hash
object_type         transaction | goal | account | category
field               field_name
reason_category     WRONG_CATEGORY | WRONG_MERCHANT | DUPLICATE | OTHER
source              USER_MANUAL
timestamp           ISO8601
downstream_updated  boolean
time_to_correct_ms  integer
\`\`\`

## Metrics to Compute (on real data)
| Metric | Formula |
|--------|---------|
| correction_rate | corrections / transactions |
| corrections_per_active_user | total corrections / active users |
| repeat_correction_rate | same field corrected > 1 / total |
| time_to_correction | median time_to_correct_ms |
| post_correction_error_rate | new errors after correction / corrections |

## Interpretation Note
High correction rate MAY indicate good user control OR poor auto-classification.
Investigate before labeling as "bad."

## Implementation
Correction telemetry hook active in \`transactions.controller.js\` via \`Telemetry.trackCorrectionCompleted()\`.

## Current Status
INSUFFICIENT_EVIDENCE — N = 0 real users.
`,

'PHASE_13_TRUST_ANALYSIS.md': `# Phase 13 — Trust Analysis

## Trust Dimensions (keep separate)
1. Financial number trust
2. AI explanation trust
3. Forecast trust
4. Privacy trust
5. Data-source trust
6. User-control trust

## Measurement Methods
| Method | Dimension |
|--------|-----------|
| Structured in-product feedback | All |
| Source/evidence inspection behavior | Data-source, AI |
| Correction behavior | Number, Data-source |
| Feature abandonment | All |
| Qualitative interviews | All |
| Repeat use | All |

## Survey Questions (§18)
- "Did you understand where this number came from?"
- "Did you understand what data was used?"
- "Would you rely on this explanation to make a financial decision?"
- "What made you distrust it?"

## Anti-patterns (not used)
- Session duration as proxy for trust
- Screen views as proxy for trust
- Click count as trust metric

## Current Status
INSUFFICIENT_EVIDENCE — N = 0 real users.
`,

'PHASE_13_AI_QUALITY.md': `# Phase 13 — AI Quality

## Quality Dimensions
| Dimension | Description |
|-----------|-------------|
| Intent accuracy | Did AI understand the question? |
| Tool correctness | Did AI select the right tool? |
| Financial numerical consistency | AI claim == deterministic tool output |
| Evidence grounding | Is the claim backed by real data? |
| Clarification quality | Does AI ask good follow-up questions? |
| Hallucination resistance | Does AI refuse unsupported claims? |
| Action safety | Does AI refuse dangerous actions? |
| Tone | Is the response appropriate? |
| Usefulness | Does it help the user make a decision? |

## Grading
| Grade | Criteria |
|-------|----------|
| Correct | Matches deterministic validator output |
| Partially correct | Directionally correct, minor error |
| Incorrect | Wrong number or wrong tool |
| Unsupported | Claim not backed by evidence |
| Unsafe | Privacy leak, unauthorized action, dangerous certainty |
| Unhelpful | Correct but does not help user decide |

## Severity
| Level | Examples |
|-------|----------|
| P0 Critical | Wrong-user data, privacy leak, unauthorized action |
| P1 Major | Material financial number incorrect, wrong tool |
| P2 Moderate | Poor explanation, missing evidence |
| P3 Minor | Copy/UI quality |

## Privacy Rule
AI interactions sampled for quality review must be minimized/redacted.
Reviewers see minimum necessary data, access logged, scope restricted.

## Current Status
INSUFFICIENT_EVIDENCE — N = 0 real users.
`,

'PHASE_13_AI_SAFETY.md': `# Phase 13 — AI Safety

## P0 Blockers (must stop rollout immediately)
- Wrong-user data exposure
- Privacy leakage of any financial PII
- Unauthorized financial action executed
- Materially wrong financial number presented with false certainty
- Policy bypass

## P1 Blockers (must be contained before cohort expansion)
- Financial number incorrect but not dangerous
- Wrong tool selected for financial decision
- Misleading certainty shown to user

## Response Protocol
\`\`\`
P0 detected:
→ STOP rollout
→ Contain: disable affected feature flag
→ Investigate root cause
→ Fix with regression test
→ Re-enable only after controlled validation
\`\`\`

## AI Safety Governance
- Feature flags provide kill switch for any AI feature
- AI provider failures return 503 (not fake data)
- AI numerical consistency validated against deterministic tool output
- No model self-evaluation — independent validators used

## Training Data Policy
Beta user conversations must NOT be used for model training without:
- Explicit consent policy
- De-identification
- Governance approval

## Current P0/P1 Incidents
= 0 (no real users yet)

## Current Status
PASS (governance implemented). Awaiting real-user validation.
`,

'PHASE_13_FORECAST_ACCURACY.md': `# Phase 13 — Forecast Accuracy (Real-World)

## Phase 8 vs Phase 13 Distinction
Phase 8 synthetic evaluation DOES NOT prove production forecast performance.
Phase 13 requires real users to generate actual forecast origins and actual outcomes.

## Forecast Evaluation Protocol
\`\`\`
forecast_generated_at T
→ actual_outcome_observed_at T+H
\`\`\`
Where H = 7d, 30d, 90d (policy-dependent).

## Eligibility Requirements (§23)
A forecast origin is valid only if:
- Required historical data exists
- Forecast was actually generated and stored
- Target outcome becomes observable
- No future data leakage
- State/version references preserved

Invalid origins must be classified: INVALID_ORIGIN (not silently dropped).

## 90-Day Policy
Phase 8 policy: FORECAST_UNAVAILABLE for low-trust long horizons.
This behavior is RETAINED in Phase 13. It must not be relaxed to generate more metrics.

## Metrics to Compute (on eligible real data)
\`\`\`
N
MAE (Mean Absolute Error)
RMSE (Root Mean Square Error)
BIAS (signed systematic error)
Coverage (% actuals within prediction interval)
Interval Width (mean)
Forecast Availability Rate
\`\`\`

Segmented by: horizon, history depth, coverage, volatility, income stability.

## Current Status
7-DAY: N-A (no real users)
30-DAY: N-A (no real users)
90-DAY: UNAVAILABLE_BY_POLICY
All metrics: INSUFFICIENT_EVIDENCE
`,

'PHASE_13_RETENTION.md': `# Phase 13 — Retention

## Definitions
| Metric | Definition |
|--------|-----------|
| D1 | Return within 24h of activation |
| D7 | Return within 7 days of activation |
| D30 | Return within 30 days of activation |

**Activation:** FIRST_TRUSTED_FINANCIAL_RESULT_VIEWED (server-side verified)
**Return:** Any meaningful product event (not just app open)

## Denominator Definition (§27)
\`\`\`
N_eligible = users who reached activation within measurement window
activation_date = date of FIRST_TRUSTED_FINANCIAL_RESULT_VIEWED event
return_window = [activation_date + 0, activation_date + D]
excluded_users = test accounts, developer accounts, synthetic traffic
\`\`\`

## Meaningful Return Reasons to Track
- AI usage
- Planning action
- Goal progress review
- New data sync triggered
- Financial review (balance/spending check)
- Forecast review

## Statistical Discipline
For every reported retention metric include:
- N eligible
- N retained
- Definition version
- Observation window
- Release/feature flag state
- Cohort

Do NOT interpret raw app opens as retained product value.

## Current Status
INSUFFICIENT_EVIDENCE — N = 0 real users.
`,

'PHASE_13_DECISION_IMPACT.md': `# Phase 13 — Decision Impact

## Honest Stance
FinCopilot must NOT claim "FinCopilot saved users ₹X" without causal evidence.

## Observable Proxies (OBSERVATIONAL — not causal)
| Proxy Event | Description |
|-------------|-------------|
| reviewed_upcoming_obligation | User viewed commitment detail |
| corrected_financial_classification | User corrected a category/merchant |
| changed_goal_contribution | User updated goal amount |
| ran_affordability_simulation | User ran what-if scenario |
| reviewed_spending_driver | User investigated a spending category |
| followed_plan | User created + executed a planning action |
| avoided_purchase_after_affordability | User ran simulation then did NOT transact |

## Labeling Rule
All proxies must be labeled: OBSERVATIONAL
Claims of causal impact require proper experimental design (controlled A/B with appropriate statistical power).

## Statistical Requirements (§36, §37, §77)
Before any causal claim, must define and validate:
- N eligible
- Baseline rate
- Variance
- Effect size
- Confidence interval / uncertainty

If unavailable: report as OBSERVATIONAL or INSUFFICIENT_EVIDENCE.

## Current Status
INSUFFICIENT_EVIDENCE — N = 0 real users.
`,

'PHASE_13_USER_RESEARCH.md': `# Phase 13 — User Research

## Research Design
Recruit actual beta participants. All sessions require:
- Informed consent for research recording
- Right to withdraw
- Data minimization — no raw financial history in notes

## Core Usability Tasks
1. Connect data source
2. Understand money state (balance, spending)
3. Ask the AI a financial question
4. Inspect evidence/source of an AI answer
5. Correct a transaction
6. Run affordability simulation
7. Review forecast
8. Review goal
9. Export / delete data

## Measurement Per Task
| Dimension | How Measured |
|-----------|-------------|
| Task completion | Binary: completed without prompting |
| Confusion | Observed hesitation, error, backtrack |
| Time on task | Wall clock |
| Confidence | Post-task rating 1-5 |
| Misunderstanding | Verbalised incorrect assumption |
| Next action | What user does after task |

## Interview Questions (§39)
DO NOT ask: "Do you like the app?"
DO ask:
- "What do you think this number means?"
- "Why do you trust/distrust this answer?"
- "What would you do next?"

## Privacy
- Transcripts redacted before storage
- Identifiers minimized
- Research notes access-controlled
- Retention policy: 90 days post-project

## Current Status
Framework defined. N = 0 sessions completed. INSUFFICIENT_EVIDENCE.
`,

'PHASE_13_EXPERIMENTS.md': `# Phase 13 — Experiment Governance

## Required Fields Per Experiment
\`\`\`
hypothesis            string
population            cohort + eligibility
control               description
variant               description
primary_metric        name + definition
secondary_metrics     list
sample_size_rationale why N is sufficient
duration              start + end/review date
stop_criteria         early stop conditions
risk                  potential harms
rollback              how to revert
owner                 name + team
\`\`\`

## Prohibited A/B Tests
Do NOT A/B test with an unsafe control/variant:
- Security authorization logic
- Deletion safety guarantees
- Financial correctness calculations
- Privacy controls

## Statistical Discipline
- Pre-define metric definitions BEFORE observing results (no metric shopping)
- Report N, effect, uncertainty, limitations with every result
- Do not declare significance from tiny samples
- Label all observational results as OBSERVATIONAL

## Current Status
No experiments running. Framework defined and ready.
`,

'PHASE_13_SUPPORT_LOOP.md': `# Phase 13 — Support Loop

## Support Classification
Every real support case is classified:
| Category | Description |
|----------|-------------|
| financial_correctness | Balance, spending, income wrong |
| data_connection | Import/sync issues |
| ai | AI answers wrong, unhelpful, or unsafe |
| privacy | Data access or deletion concern |
| security | Suspected unauthorized access |
| ux | Interface confusion |
| performance | Slowness, timeout |

## Support → Engineering Loop
\`\`\`
Issue filed
→ Classification + Severity (P0-P3)
→ Owner assigned
→ Root cause investigation
→ Fix implemented
→ Regression test written
→ Controlled release
→ Issue resolved + linked to release
\`\`\`

## No Silent Hotfixes
No production behavior change without recording:
- The material change
- The reason
- The linked support issue

## P0/P1 Response
- P0: Contain immediately (disable flag), investigate, communicate
- P1: Owner assigned within 1 business day, contained before cohort expansion

## Current Status
Support loop defined. N = 0 issues (no real users yet).
`,

'PHASE_13_INCIDENT_LEARNINGS.md': `# Phase 13 — Incident Learnings

## Incident Protocol
\`\`\`
detect
→ contain (disable feature flag if needed)
→ communicate (internal + user-facing if impacted)
→ recover
→ document
→ prevent recurrence (regression test)
\`\`\`

## No Silent Fixes
No incident may be silently fixed in production.
Every material fix must be:
- Recorded in incident log
- Linked to a regression test
- Linked to a release

## Incident Privacy Rule
Incident reports must NOT include:
- Full transaction dumps
- Raw AI conversations
- Unnecessary PII
Use sanitized references only.

## AI Failure Taxonomy (§34)
| Class | Description |
|-------|-------------|
| Factual | Wrong information stated as fact |
| Numerical | Wrong financial number |
| Evidence | Claim not grounded in user data |
| Intent | Misunderstood user question |
| Tool | Wrong tool selected |
| Policy | Safety/privacy rule bypassed |
| Hallucination | Invented information |
| Context | Wrong user context used |
| Privacy | PII exposure |
| UX | Confusing output |
| Latency | Timeout/degradation |
| Cost | Abnormal token consumption |

## Current Incidents
P0: 0
P1: 0
Known issues: None
`,

'PHASE_13_PRIVACY_ANALYTICS.md': `# Phase 13 — Privacy Analytics

## Core Rules
1. User identifiers are SHA-256 hashed (salted) before any analytics storage
2. PII fields are stripped in \`Telemetry.deepStripPII()\` — including: balance, amount, accountNumber, rawPrompt, conversation, IBAN, PAN, tokens
3. No raw bank statements, full transaction histories, or complete AI conversations in analytics
4. Test/synthetic traffic is labeled with TrafficClass and excluded from real-user aggregations

## Event Design
Analytics events contain only:
\`\`\`
event_type        string
feature           string
status            string
latency_ms        integer
traffic_class     REAL_USER | SYNTHETIC | ...
timestamp         ISO8601
\`\`\`

## AI Conversation Policy (§48)
Beta user conversations must NOT be used for model training without:
- Explicit consent policy
- De-identification approval
- Governance sign-off

Current status: POLICY_REQUIRED — not proceeding with training use.

## Deletion Compliance (§49)
When beta user deletes account:
- Telemetry anon_user hash is re-salted (breaks historical linkage)
- Research data follows 90-day retention policy
- Raw analytics purged per data retention schedule

## Current Status
Privacy controls: PASS
Test traffic isolation: PASS
`,

'PHASE_13_EVIDENCE_SNAPSHOT.md': `# Phase 13 — Beta Evidence Snapshot

## Snapshot Details
\`\`\`
ID:       SNAP-2026-08-27-02
Version:  1.0.1
Created:  2026-08-27T21:00:00Z
Hash:     a3460569f2d81982a4c0ecf62836ae2367fcd8b674b8117615281952e1caa9ee
Algorithm: SHA-256
File:     docs/PHASE_13_EVIDENCE_SNAPSHOT.json
\`\`\`

## Hash Integrity
The hash is computed from a deterministic canonical JSON serialization of the snapshot content.
Repeated generation of identical content produces identical hash.

> [!IMPORTANT]
> This is a REAL cryptographic hash of actual infrastructure-readiness evidence.
> The [HASH] placeholder has been replaced.

## Contents
- Snapshot version and release reference
- Cohort definition and eligibility rules
- Feature flag state at time of freeze
- Metric definitions (pre-defined before analysis)
- Aggregate evidence (all INSUFFICIENT_EVIDENCE — N = 0 real users)
- Infrastructure evidence (all PASS)
- Security/privacy state
- Incident summary
- Known limitations

## Known Limitations (Honest)
1. REAL_USERS = 0 — all user-facing metrics are INSUFFICIENT_EVIDENCE
2. Region/age eligibility policy not yet defined (POLICY_REQUIRED)
3. 90-day forecast evaluation requires minimum 3 months of history — UNAVAILABLE_BY_POLICY
4. Decision Impact causal claims require proper experimental design — not yet run
`,

'PHASE_13_FINAL_CLOSURE_REPORT.md': `# Phase 13 — Final Closure Report

## Status
\`\`\`
PHASE 13 FINAL STATUS = OPEN
\`\`\`

Phase 13 is NOT declared VERIFIED_COMPLETE.

## Reason
> [!CAUTION]
> REAL BETA USERS = 0
> Per the Phase 13 master prompt §62, §64:
> "REAL USERS = 0 + TELEMETRY EXISTS + TESTS PASS ≠ PHASE 13 VERIFIED_COMPLETE"
> This equivalence is explicitly forbidden.

## What IS Complete
| Item | Status |
|------|--------|
| Telemetry infrastructure (TrafficClass isolation) | ✅ PASS |
| Feature flag middleware (DB-backed cohort) | ✅ PASS |
| Beta cohort assignment service | ✅ PASS |
| beta_cohort_assignments migration | ✅ PASS |
| Performance middleware (P95 tracking) | ✅ PASS |
| Data quality endpoint | ✅ PASS |
| Correction telemetry hooks | ✅ PASS |
| Forecast telemetry hooks | ✅ PASS |
| Evidence snapshot (real SHA-256 hash) | ✅ PASS |
| 18 Phase 13 documentation files | ✅ PASS |
| Security / privacy controls | ✅ PASS |
| Phase 0–12 regression | ✅ PASS |
| Fake/hardcoded metrics | ✅ = 0 |
| Unauthorized data use | ✅ = 0 |

## What Requires Real Users
| Metric | Status |
|--------|--------|
| Onboarding funnel | INSUFFICIENT_EVIDENCE |
| Data quality | INSUFFICIENT_EVIDENCE |
| Connection/sync quality | INSUFFICIENT_EVIDENCE |
| Correction quality | INSUFFICIENT_EVIDENCE |
| Trust analysis | INSUFFICIENT_EVIDENCE |
| AI quality | INSUFFICIENT_EVIDENCE |
| AI numerical consistency | INSUFFICIENT_EVIDENCE |
| Forecast real-world evaluation | INSUFFICIENT_EVIDENCE |
| Retention (D1/D7/D30) | INSUFFICIENT_EVIDENCE |
| Decision impact | INSUFFICIENT_EVIDENCE |

## Phase 14 Entry Condition
Phase 14 may begin ONLY when:
\`\`\`
REAL BETA USERS > 0
AND all P0 incidents = 0
AND user-facing metrics have enough evidence to make honest claims
\`\`\`

OR if the project authority explicitly records a decision to change the phase strategy.

## Recommendation
Begin INTERNAL cohort onboarding. Instrument INTERNAL test team as beta_role = INTERNAL.
Collect real telemetry from them. Validate onboarding funnel, data quality, and correction loop.
Only then can Phase 13 be VERIFIED_COMPLETE.
`
};

if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
}

let count = 0;
for (const [filename, content] of Object.entries(docs)) {
    fs.writeFileSync(path.join(docsDir, filename), content);
    console.log(`✅ Created ${filename}`);
    count++;
}
console.log(`\n📚 Total: ${count} Phase 13 documents written.`);
