"use client";

import * as React from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Sparkles } from "lucide-react";
import { useAppData } from "@/hooks/use-app-data";

import { Badge } from "@/components/shared";
import { timeAgo } from "@/lib/format";

export default function InsightDetailPage() {
  const { aiInsights } = useAppData();
  const params = useParams<{ id: string }>();
  const insight = aiInsights.find((i) => i.insight_id === params.id) ?? aiInsights[0];

  return (
    <div className="flex flex-col gap-6 max-w-2xl mx-auto">
      <header className="flex items-center gap-3">
        <Link href="/ai" className="w-9 h-9 rounded-[10px] flex items-center justify-center border border-[var(--border)] hover:bg-[var(--surface-2)] transition-colors">
          <ArrowLeft className="w-4 h-4" />
        </Link>
        <div className="flex items-center gap-2">
          <div className="w-9 h-9 rounded-[10px] bg-linear-to-br from-accent to-(--gold) flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-[#0A0F0D]" />
          </div>
          <div>
            <h1 className="font-display font-bold text-[18px] leading-tight">AI Insight</h1>
            <p className="text-[11px] font-mono text-[var(--text-muted)] uppercase tracking-wider">
              Generated {timeAgo(insight.generated_at)}
            </p>
          </div>
        </div>
      </header>

      <section className="premium-card p-6 flex flex-col gap-4">
        <div className="flex items-center justify-between">
          <h2 className="font-display font-semibold text-[20px] leading-tight">{insight.title}</h2>
          <Badge label={`${insight.confidence}% conf`} variant="ai" />
        </div>
        <p className="text-[15px] text-(--text-secondary) leading-[1.6]">{insight.summary}</p>
        {insight.tags && insight.tags.length > 0 && (
          <div className="flex flex-wrap gap-2">
            {insight.tags.map((tag) => (
              <Badge key={tag} label={tag} variant={tag === "warning" ? "warning" : "neutral"} />
            ))}
          </div>
        )}
      </section>

      <section className="premium-card p-6 flex flex-col gap-3">
        <h3 className="text-[11px] font-mono uppercase tracking-wider text-[var(--text-muted)]">Evidence</h3>
        <p className="text-[14px] text-(--text-secondary) leading-[1.6]">{insight.evidence}</p>
      </section>

      {insight.actions && insight.actions.length > 0 && (
        <section className="flex flex-col gap-3">
          <h3 className="text-[11px] font-mono uppercase tracking-wider text-[var(--text-muted)]">Suggested actions</h3>
          {insight.actions.map((action, i) => (
            <Link
              key={i}
              href={action.href}
              className="premium-card p-4 flex items-center justify-between group hover:border-[var(--border-strong)] transition-colors"
            >
              <span className="text-[14px] font-medium">{action.label}</span>
              <span className="text-[12px] text-accent group-hover:translate-x-0.5 transition-transform">→</span>
            </Link>
          ))}
        </section>
      )}

      <p className="text-center text-[11px] text-[var(--text-muted)] mt-4">
        This insight was generated by FinCopilot AI. Always review before taking action.
      </p>
    </div>
  );
}
