"use client";
import { ValueBars } from '@/components/charts/value-bars';
import { useState } from 'react';
import { api } from '@/lib/api';
import { amount, label, object, rows } from '@/lib/response';
import { formatPaise } from '@/lib/format';
import { useResource } from '@/hooks/use-resource';
import { ResourceState } from '@/components/shared/resource-state';

async function loadBudgets(){return rows(object(await api.getBudgets()).budgets);}
export default function BudgetsPage(){
  const state=useResource(loadBudgets);
  const [period,setPeriod]=useState('monthly');
  const [category,setCategory]=useState(''); const [limit,setLimit]=useState('');
  const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const save=async(event:React.FormEvent)=>{event.preventDefault();setError(null);
    if(!/^\d+(\.\d{1,2})?$/.test(limit)||Number(limit)<=0){setError('Enter a positive amount with up to two decimal places.');return;}
    setBusy(true);try{await api.createBudget({category:category.trim(),budgeted_paise:Math.round(Number(limit)*100),period});setCategory('');setLimit('');state.reload();}catch(error){setError(error instanceof Error?error.message:'Could not save budget.');}finally{setBusy(false);}};
  return <main className="max-w-5xl mx-auto flex flex-col gap-6 pb-12"><header><h1 className="font-display text-4xl font-semibold">Spending guardrails</h1><p className="text-(--text-secondary) mt-2">Set period-specific limits and compare them with recorded spending.</p></header>
    <form onSubmit={save} className="premium-card p-6 flex flex-col gap-4"><h2 className="font-semibold">Create or update a category limit</h2><label className="text-sm">Category<input required maxLength={80} value={category} onChange={e=>setCategory(e.target.value)} className="block w-full rounded-xl border border-(--border) bg-(--surface) p-3 mt-2" placeholder="e.g. groceries" /></label><label className="text-sm">Period<select value={period} onChange={e=>setPeriod(e.target.value)} className="block w-full rounded-xl border border-(--border) bg-(--surface) p-3 mt-2">{["monthly","weekly","yearly"].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label className="text-sm">Limit in rupees<input required inputMode="decimal" value={limit} onChange={e=>setLimit(e.target.value)} className="block w-full rounded-xl border border-(--border) bg-(--surface) p-3 mt-2" placeholder="0.00" /></label>{error&&<p role="alert" className="text-red-500 text-sm">{error}</p>}<button disabled={busy} className="self-start bg-accent text-accent-foreground px-5 py-2.5 rounded-xl disabled:opacity-50">{busy?'Saving…':'Save budget'}</button></form>
    <ResourceState loading={state.loading} error={state.error} retry={state.reload}/>
    {state.data&&<section className="grid sm:grid-cols-3 gap-3">{[{title:'Category limits',value:String(state.data.length)},{title:'Over the limit',value:String(state.data.filter(item=>item.status==='over').length)},{title:'Close to the limit',value:String(state.data.filter(item=>item.status==='warning').length)}].map(item=><div key={item.title} className="premium-card p-5"><p className="text-xs text-(--text-secondary)">{item.title}</p><p className="font-display text-3xl font-semibold mt-2">{item.value}</p></div>)}</section>}
    {state.data&&<ValueBars title="Your category allocations" description="Saved limits by category and budget period. These are planning targets, not account balances." data={state.data.map(budget=>({name:`${label(budget.category)} / ${label(budget.period)}`,value:amount(budget.budgeted_paise)}))}/>}
    {state.data&&<section className="premium-card p-6">{!state.data.length?<p>No budgets saved yet.</p>:state.data.map(budget=>{const spent=amount(budget.spent_paise);const budgeted=amount(budget.budgeted_paise);const pct=spent!==null&&budgeted!==null&&budgeted>0?Math.round(spent/budgeted*100):null;return <article key={label(budget.budget_id)} className="py-5 border-b border-(--border) last:border-0"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="font-semibold capitalize">{label(budget.category)}</h2><p className="text-xs text-(--text-secondary) mt-1">{label(budget.period)} / {label(budget.status).replaceAll('_',' ')}</p></div><p className="tabular-nums text-sm">{spent===null?'Unavailable':formatPaise(spent)} / {budgeted===null?'Unavailable':formatPaise(budgeted)}</p></div><div role="progressbar" aria-label={`${label(budget.category)} budget used`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={pct===null?undefined:Math.max(0,Math.min(100,pct))} aria-valuetext={pct===null?'Unavailable':`${pct}% of limit used`} className="h-2.5 mt-4 rounded-full bg-(--surface-subtle) overflow-hidden"><div className={`h-full rounded-full transition-all ${pct!==null&&pct>100?'bg-(--negative)':'bg-accent'}`} style={{width:`${Math.max(0,Math.min(100,pct??0))}%`}}/></div><div className="flex flex-wrap justify-between items-center gap-3 mt-3"><p className="text-xs text-(--text-secondary)">{spent===null||budgeted===null?'Remaining amount unavailable':spent>budgeted?`${formatPaise(spent-budgeted)} over the limit`:`${formatPaise(budgeted-spent)} remaining`}</p><button onClick={()=>{setPeriod(label(budget.period,'monthly'));setCategory(label(budget.category,''));setLimit(budgeted===null?'':(budgeted/100).toFixed(2));document.querySelector<HTMLInputElement>('input')?.focus();}} className="min-h-11 px-3 text-sm text-accent">Adjust limit</button></div></article>;})}</section>}
  </main>;
}
