"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowLeft, Landmark, Loader2, ShieldCheck } from "lucide-react";
import { api, ApiError } from "@/lib/api";

export default function ConnectAccountPage() {
  const [mobile, setMobile] = React.useState("");
  const [submitting, setSubmitting] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  async function startConsent(event: React.FormEvent) {
    event.preventDefault();
    setError(null);
    const normalized = mobile.replace(/\D/g, "");
    if (normalized.length < 10 || normalized.length > 15) {
      setError("Enter the mobile number registered with your financial institution.");
      return;
    }

    setSubmitting(true);
    try {
      const result = await api.initiateAAConsent({
        vua: normalized,
        redirectUrl: `${window.location.origin}/accounts/connect/callback`,
      });
      // The redirect URL is generated by Setu. Do not construct AA URLs in the client.
      window.location.assign(result.redirectUrl);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Could not start the secure account connection.");
      setSubmitting(false);
    }
  }

  return (
    <div className="mx-auto flex w-full max-w-xl flex-col gap-6 pb-12">
      <div className="flex items-center gap-3">
        <Link href="/you/connections" aria-label="Back to connections" className="flex h-9 w-9 items-center justify-center rounded-[10px] hover:bg-(--surface-subtle)">
          <ArrowLeft className="h-5 w-5" />
        </Link>
        <div>
          <h1 className="font-display text-[24px] font-bold tracking-[-0.02em]">Connect your accounts</h1>
          <p className="mt-0.5 text-[13px] text-(--text-secondary)">Secure, consent-based connection through the Account Aggregator network.</p>
        </div>
      </div>

      <section className="premium-card flex flex-col gap-5 p-6">
        <div className="flex items-start gap-3">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-[12px] bg-[var(--accent-light)]">
            <Landmark className="h-5 w-5 text-accent" />
          </div>
          <div>
            <h2 className="font-display text-[16px] font-semibold">Account Aggregator connection</h2>
            <p className="mt-1 text-[13px] leading-relaxed text-(--text-secondary)">
              You will be redirected to Setu&apos;s Account Aggregator consent journey, where you choose which eligible accounts to link and approve the requested data access.
            </p>
          </div>
        </div>

        <form onSubmit={startConsent} className="flex flex-col gap-3">
          <label htmlFor="aa-mobile" className="text-[12px] font-semibold text-(--text-secondary)">Mobile number</label>
          <input
            id="aa-mobile"
            inputMode="numeric"
            autoComplete="tel"
            value={mobile}
            onChange={(e) => setMobile(e.target.value)}
            placeholder="Mobile linked to your bank"
            className="h-11 rounded-[11px] border border-(--border-subtle) bg-transparent px-3 text-[14px] outline-none focus:border-accent"
          />
          {error && <p role="alert" className="text-[12px] text-(--negative)">{error}</p>}
          <button
            type="submit"
            disabled={submitting}
            className="mt-1 inline-flex h-11 items-center justify-center gap-2 rounded-[11px] bg-accent px-4 text-[14px] font-semibold text-accent-foreground disabled:opacity-60"
          >
            {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <ShieldCheck className="h-4 w-4" />}
            {submitting ? "Starting secure connection…" : "Continue securely"}
          </button>
        </form>
      </section>

      <div className="premium-card p-4 text-[12px] leading-relaxed text-(--text-tertiary)">
        FinCopilot only requests data covered by the consent shown in the Account Aggregator flow. You can reject the request or later revoke an active consent. Your financial calculations continue to be performed by FinCopilot&apos;s deterministic finance engine.
      </div>
    </div>
  );
}
