"use client";
import { useState } from 'react';
import { useTheme } from 'next-themes';
import { motion } from 'framer-motion';
import { Moon, Sun, Monitor, Bell, SlidersHorizontal, Check, Globe } from 'lucide-react';
import { api } from '@/lib/api';
import { object, label } from '@/lib/response';
import { useResource } from '@/hooks/use-resource';
import { ResourceState } from '@/components/shared/resource-state';
const load=async()=>object(object(await api.getPreferences()).preferences);
export default function PreferencesPage(){
 const state=useResource(load);const {setTheme}=useTheme();const [saving,setSaving]=useState<string|null>(null);const [feedback,setFeedback]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
 const save=async(patch:Record<string,unknown>,key:string)=>{setSaving(key);setError(null);setFeedback(null);try{await api.updatePreferences(patch);if(typeof patch.theme==='string')setTheme(patch.theme);if(typeof patch.density==='string')document.documentElement.dataset.density=patch.density;setFeedback('Your preferences have been saved.');state.reload();}catch(error){setError(error instanceof Error?error.message:'Unable to save preferences.');}finally{setSaving(null);}};
 const prefs=state.data;
 return <div className="max-w-4xl mx-auto flex flex-col gap-7 pb-12"><header><p className="text-xs uppercase tracking-[.2em] text-accent">Make it feel like you</p><h1 className="font-display text-3xl sm:text-4xl font-bold mt-3">Your preferences</h1><p className="mt-3 text-sm text-(--text-secondary)">A workspace that fits your eyes, your rhythm and your routine.</p></header><ResourceState loading={state.loading} error={state.error} retry={state.reload}/>{error&&<p role="alert" className="premium-card p-4 text-red-500">{error}</p>}{feedback&&<p role="status" className="text-sm text-(--positive) flex gap-2"><Check className="w-4 h-4"/>{feedback}</p>}
 {prefs&&<><motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="premium-card p-5 sm:p-7"><div className="flex items-center gap-3"><div className="p-3 rounded-xl bg-accent/10"><Sun className="w-5 h-5 text-accent"/></div><div><h2 className="text-lg font-semibold">A different light</h2><p className="text-sm text-(--text-secondary)">Choose your preferred appearance.</p></div></div><div className="grid grid-cols-3 gap-3 mt-6">{[{value:'light',title:'Daylight',Icon:Sun},{value:'dark',title:'After hours',Icon:Moon},{value:'system',title:'With your device',Icon:Monitor}].map(({value,title,Icon})=><button key={value} disabled={saving!==null} aria-pressed={prefs.theme===value} onClick={()=>save({theme:value},'theme')} className={`rounded-2xl border p-3 sm:p-5 text-left transition-all hover:-translate-y-0.5 ${prefs.theme===value?'border-accent bg-accent/5':'border-(--border)'}`}><div className={`rounded-lg h-16 sm:h-24 p-2 ${value==='dark'?'bg-slate-900':value==='light'?'bg-slate-100':'bg-linear-to-br from-slate-100 to-slate-900'}`}><div className="h-full w-1/4 rounded bg-emerald-500/30"/></div><Icon className="w-4 h-4 mt-4 text-accent"/><p className="text-xs sm:text-sm font-semibold mt-2">{title}</p></button>)}</div></motion.section>
 <section className="premium-card p-5 sm:p-7"><h2 className="text-lg font-semibold flex items-center gap-2"><SlidersHorizontal className="w-5 h-5 text-accent"/>Room to breathe</h2><p className="text-sm text-(--text-secondary) mt-2">Choose how closely information sits together.</p><div className="grid sm:grid-cols-2 gap-3 mt-5">{['comfortable','compact'].map(value=><button key={value} aria-pressed={prefs.density===value} disabled={saving!==null} onClick={()=>save({density:value},'density')} className={`rounded-xl p-4 text-left border ${prefs.density===value?'border-accent bg-accent/5':'border-(--border)'}`}><span className="font-medium capitalize">{value}</span><p className="text-xs text-(--text-secondary) mt-2">{value==='comfortable'?'More space around cards and rows.':'More information within each view.'}</p></button>)}</div></section>
 <section className="premium-card p-5 sm:p-7"><h2 className="text-lg font-semibold flex gap-2 items-center"><Bell className="w-5 h-5 text-accent"/>What deserves your attention</h2><p className="text-sm text-(--text-secondary) mt-2">Choose which event categories you want to hear about.</p><div className="mt-4 divide-y divide-(--border)">{['bills','insights','goals','alerts','streaks'].map(event=>{const events=object(prefs.notification_events);const enabled=events[event]===true;return <div key={event} className="flex items-center justify-between gap-4 py-4"><span className="capitalize text-sm font-medium">{event}</span><button role="switch" aria-checked={enabled} aria-label={`${event} notifications`} disabled={saving!==null} onClick={()=>save({notification_events:{...events,[event]:!enabled}},event)} className={`h-11 w-14 flex items-center rounded-full p-1.5 transition-colors ${enabled?'bg-accent':'bg-(--surface-subtle)'}`}><span className={`h-8 w-8 rounded-full bg-white shadow transition-transform ${enabled?'translate-x-3':''}`}/></button></div>;})}</div></section>
 <section className="premium-card p-5 sm:p-7"><h2 className="text-lg font-semibold flex gap-2 items-center"><Globe className="w-5 h-5 text-accent"/>Regional defaults</h2><div className="grid sm:grid-cols-2 gap-4 mt-5"><div className="rounded-xl bg-(--surface-subtle) p-4"><p className="text-xs text-(--text-secondary)">Ledger currency</p><p className="font-semibold mt-2">{label(prefs.currency)} · Indian rupee</p></div><div className="rounded-xl bg-(--surface-subtle) p-4"><p className="text-xs text-(--text-secondary)">Display language</p><p className="font-semibold mt-2">{prefs.language==='en'?'English':label(prefs.language)}</p></div></div></section></>}
 </div>;
}
